### ISSUE TITLE
Incorrect function arguments will cause Node to crash

### ISSUE THREAD

**Issue by rcjsuen** [nodegit/nodegit#1183] opened 2017-01-07 05:14 UTC
Please run the code below and your Node will crash. No exceptions will be logged at all.
```
var git = require(".");
var repoPath = "myRepo";
var repo = null;

git.Repository.open(repoPath)
.then(function(r) {
    console.log("repo opened");
    repo = r;
    return git.Reference.lookup(repo, "refs/heads/master", null)
      .then(function(ref) {
        console.log("ref lookup");
        return repo.getReferenceCommit(ref);
      })
      .then(function(commit) {
        console.log("ref commit retrieved");
        return git.Branch.createFromAnnotated(repo, "v0.2", /* wrong arg */ commit, 1);
      }).then(function(commit) {
        console.log("done");
      }, function(err) {
        console.log(err);
      });
});
```
```
nodegit.node!create_branch(git_reference * * ref_out, git_repository * repository, const char * branch_name, const git_commit * commit, const char * from, int force) Line 68	C
nodegit.node!GitBranch::CreateFromAnnotated(const Nan::FunctionCallbackInfo<v8::Value> & info) Line 318	C++
nodegit.node!Nan::imp::FunctionCallbackWrapper(const v8::FunctionCallbackInfo<v8::Value> & info) Line 175	C++
node.exe!00007ff6e16acef9()	Unknown
```

**Comment by rcjsuen** [comment] 2017-01-07 05:35
See #1070 for a similar instance of this type of bug.

**Comment by johnhaley81** [comment] 2017-01-27 15:25
Dupe of #1070.

Please follow #1127 for updates.

**Closed by johnhaley81** 2017-01-27 15:25 UTC
