### ISSUE TITLE
npm install failed at the nodegit@0.14.1 preinstall script 'node lifecycleScripts/preinstall'.

### ISSUE THREAD

**Issue by victorbutler** [nodegit/nodegit#1102] opened 2016-08-09 08:52 UTC
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Node v6.3.1
NPM v3.10.5
NodeGit v0.14.1
[npm-debug.log.txt](https://github.com/nodegit/nodegit/files/408538/npm-debug.log.txt)
---
I'm having some trouble installing nodegit on my RHEL7 machine. Works fine on my Mac locally, but when I execute on RHEL7, it dies. The following is the console output, which is different than the npm-debug log (attached above). I searched for a solution, but found another issue referring to nodegit v0.13 (#1037). I'm using v0.14 so I figured I'd open another issue. Please close this one if they can be combined.

```
$ npm install

> nodegit@0.14.1 preinstall /var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e/vendor/libssh2/configure --with-libssl-prefix=/var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e/vendor/libssh2/configure --with-libssl-prefix=/var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e/vendor/openssl/openssl' }
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e/vendor/libssh2/configure --with-libssl-prefix=/var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e/vendor/libssh2/configure --with-libssl-prefix=/var/nginx/auto-builder/node_modules/.staging/nodegit-e0e9580e/vendor/openssl/openssl' }
nodejs-gitlab-bot@0.1.0 /var/nginx/auto-builder
├── d@0.1.1  extraneous
└─┬ rimraf@2.5.4
  └─┬ glob@7.0.5
    ├── fs.realpath@1.0.0
    ├─┬ inflight@1.0.5
    │ └── wrappy@1.0.2
    ├── inherits@2.0.1
    ├─┬ minimatch@3.0.3
    │ └─┬ brace-expansion@1.1.6
    │   ├── balanced-match@0.4.2
    │   └── concat-map@0.0.1
    ├── once@1.3.3
    └── path-is-absolute@1.0.0

npm WARN nodejs-gitlab-bot@0.1.0 license should be a valid SPDX license expression
npm ERR! Linux 3.10.0-327.22.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.14.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.14.1 preinstall script 'node lifecycleScripts/preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/nginx/auto-builder/npm-debug.log
```

**Comment by johnhaley81** [comment] 2016-08-10 14:31
Great write up but I do think this is a dupe of #1037. Closing out. Thanks @victorbutler!

**Closed by johnhaley81** 2016-08-10 14:31 UTC
