### ISSUE TITLE
ELIFECYCLE error on `npm rebuild`

### ISSUE THREAD

**Issue by emosesSfdc** [nodegit/nodegit#578] opened 2015-05-18 23:29 UTC
After doing `npm rebuild`, I see this: 

```
> nodegit@0.4.0 install /Users/emoses/dev/sfdc-matrix/keymaker/node_modules/nodegit
> node lifecycleScripts/install

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/emoses/dev/sfdc-matrix/keymaker/node_modules/nodegit/lifecycleScripts/install'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 12.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! nodegit@0.4.0 install: `node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.4.0 install script 'node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.
```

From npm-debug.log: 

```
6583 info build /Users/emoses/dev/sfdc-matrix/keymaker/node_modules/nodegit
6584 info preinstall nodegit@0.4.0
6585 verbose linkStuff [ false,
6585 verbose linkStuff   false,
6585 verbose linkStuff   false,
6585 verbose linkStuff   '/Users/emoses/dev/sfdc-matrix/keymaker/node_modules' ]
6586 info linkStuff nodegit@0.4.0
6587 verbose linkBins nodegit@0.4.0
6588 verbose linkMans nodegit@0.4.0
6589 verbose rebuildBundles nodegit@0.4.0
6590 verbose rebuildBundles [ 'nodegit-promise', 'promisify-node' ]
6591 info install nodegit@0.4.0
6592 verbose unsafe-perm in lifecycle true
6593 info nodegit@0.4.0 Failed to exec install script
6594 verbose stack Error: nodegit@0.4.0 install: `node lifecycleScripts/install`
6594 verbose stack Exit status 1
6594 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
6594 verbose stack     at EventEmitter.emit (events.js:110:17)
6594 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
6594 verbose stack     at ChildProcess.emit (events.js:110:17)
6594 verbose stack     at maybeClose (child_process.js:1015:16)
6594 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
6595 verbose pkgid nodegit@0.4.0
6596 verbose cwd /Users/emoses/dev/sfdc-matrix/keymaker
6597 error Darwin 12.6.0
6598 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
6599 error node v0.12.2
6600 error npm  v2.7.4
6601 error code ELIFECYCLE
6602 error nodegit@0.4.0 install: `node lifecycleScripts/install`
6602 error Exit status 1
6603 error Failed at the nodegit@0.4.0 install script 'node lifecycleScripts/install'.
6603 error This is most likely a problem with the nodegit package,
6603 error not with npm itself.
6603 error Tell the author that this fails on your system:
6603 error     node lifecycleScripts/install
6603 error You can get their info via:
6603 error     npm owner ls nodegit
6603 error There is likely additional logging output above.

```

**Comment by maxkorp** [comment] 2015-05-18 23:30
Fixed in master, dupe of https://github.com/nodegit/nodegit/issues/576

**Closed by maxkorp** 2015-05-18 23:30 UTC
