### ISSUE TITLE
nodegit and nw.js

### ISSUE THREAD

**Issue by olivierlesnicki** [nodegit/nodegit#557] opened 2015-05-01 20:07 UTC
Following error happens when I try to access nodegit from a nw app:
```
[72684:0501/210709:ERROR:nw_shell.cc(335)] Error: Cannot find module '../build/Debug/nodegit'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/Users/pro/Workbench/Centrica/sandbox/liteci/node_modules/nodegit/lib/nodegit.js:12:12)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
[72684:0501/210709:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module '../build/Debug/nodegit'", source: module.js (329)
```

**Comment by maxcnunes** [comment] 2015-05-02 11:56
I have the same problem with electron. Even following the installation guide: http://www.nodegit.org/guides/install/electron/

**Comment by bso-intel** [comment] 2015-05-02 17:26
I have the same problem.

**Comment by maxkorp** [comment] 2015-05-06 00:05
Electron builds are a bit tricky at the moment. Cant comment as to nw.js. We currently have a somewhat intelligent build system, which tries to determine what to build for, but I think that's going to have to go away soon possibly, in lieu of just using apm, and whatever nw.js comes up with/already has for a solution.

**Comment by tbranyen** [comment] 2015-05-11 15:53
Closed as duplicate of https://github.com/nodegit/nodegit/issues/519

**Closed by tbranyen** 2015-05-11 15:53 UTC
