### ISSUE TITLE
npm install fails with "GLIBCXX_3.4.20 not found" when using node-6.6-wheezy docker image.

### ISSUE THREAD

**Issue by kevinludwig** [nodegit/nodegit#1131] opened 2016-09-20 18:19 UTC
As stated in title. The error is below:

```
[nodegit] WARN - Could not finish postinstall
{ Error: Command failed: node /opt/app/node_modules/nodegit/dist/nodegit.js
/opt/app/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/app/node_modules/nodegit/build/Release/nodegit.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/app/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /opt/app/node_modules/nodegit/dist/nodegit.js' }
```

**Comment by saper** [comment] 2016-11-26 18:02
Looks like #1150 is the same.

**Comment by maxkorp** [comment] 2017-01-30 18:18
yeah I know #1150 is duplicate of this, but it has feedback, so I'm going to close this one in lieu of that.

**Closed** 2017-01-30 18:19 UTC
