### ISSUE TITLE
diff example not working (TypeError: Object [object Object] has no method 'then')

### ISSUE THREAD

**Issue by ttz21** [nodegit/nodegit#639] opened 2015-07-08 21:14 UTC
Hi, I'm using nodegit for the first time in a meteor app, and have been trying your example code (add-and-commit.js, create-new-repo.js, read-file.js all work great for me), but I get the following error for diff-commits.js:

 throw e;
^
TypeError: Object [object Object] has no method 'then'

This is coming from line 23 of your code," diff.patches().then(function(patches) { "

I couldn't find the commit.getDiff() documentation, so would also be grateful for insight into how to work with the 'diffList' object that is returned. Thanks for your help.

**Comment by rcjsuen** [comment] 2017-01-06 05:14
Is the example still broken, @ttz21? I ran `examples/diff-commits.js` today and it completed without any errors.

**Comment by johnhaley81** [comment] 2017-01-27 14:00
Dupe of #673

**Closed by johnhaley81** 2017-01-27 14:00 UTC
