### ISSUE TITLE
Symbol not found on macOS Sierra

### ISSUE THREAD

**Issue by tommoor** [nodegit/nodegit#1622] opened 2019-02-06 06:07 UTC
## System information
  - node version: 10
  - OS/version/architecture: macOS Sierra 10.12
  - Applicable nodegit version: 0.23.0

We have an `Electron 4.0` application that works fine on all newer versions of macOS, however on Sierra (and possibly below?) this error is thrown at runtime:

```
Error: dlopen(/Applications/AppName.app/Contents/Resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node, 1): Symbol not found: _EVP_aes_128_cbc
  Referenced from: /Applications/AppName.app/Contents/Resources/app.asar.unpacked/node_mod…
  at Object.<anonymous>(nodegit.js:12:12)
  at Object.<anonymous>(nodegit.js:1145:3)
```

---

Would love any pointers you might have…

Edit: We've confirmed this is the case on other macOS versions older than Sierra such as El Capitan.

**Comment by implausible** [comment] 2019-02-06 16:21
We need to start building the prebuilts for it. I'll see what I can do.

**Comment by implausible** [comment] 2019-02-06 19:16
Hmm, seems there are some issues with even building for electron 4. Something major must have changed. I wonder if they started exporting boringssl.

**Comment by tommoor** [comment] 2019-02-07 16:02
Please see this comment for some additional info on the changes in 4.X

https://github.com/electron/electron/issues/16195#issuecomment-450990183

**Comment by implausible** [comment] 2019-02-07 18:01
Aha so what happened is that the electron team has moved from naming their folders `iojs-x.y.z` to `x.y.z`, and now it's not as easily possible to determine that we're building for electron and not regular node. Wonderful!

**Comment by implausible** [comment] 2019-02-07 18:04
Aha, so since they switched their naming, they also started providing variables in the config.gypi file which tells us whether it was built_with_electron or not. Hopefully I can get a patch out for 0.23.1 and 0.24.1 shortly. Sorry for the inconvenience!

**Comment by implausible** [comment] 2019-02-07 19:19
I'll see if I run an alpha release for nodegit 0.25.0, if I can get it to build on Electron 4 and get back to you!

**Comment by nornagon** [comment] 2019-02-07 19:58
Duplicate of #13176

We don't currently export BoringSSL symbols from the Electron binary.

**Comment by implausible** [comment] 2019-02-07 22:41
No problem! I just initially went there out of intuition, because I can imagine boringssl + openssl symbols fighting to the death.

**Comment by tommoor** [comment] 2019-02-09 02:02
@implausible what is your current thinking on the cause of this? Sorry to be a hassle but this is a critical issue in our end. I'm thinking of maybe forking NodeGit and trying to create a version that has Node 10 support but loses the changes to OpenSSL – do you think that's even plausible based on your knowledge of the codebase?

**Comment by tommoor** [comment] 2019-02-11 02:52
Found [the original PR](https://github.com/nodegit/nodegit/pull/1545), it looks like the two are tightly entwined 😢 

Also, had to laugh: 
https://github.com/nodegit/nodegit/pull/1545#issuecomment-427589954

**Comment by implausible** [comment] 2019-02-11 15:45
The codebase definitely has Node 10 support as of today. This is purely caused by the change in header location in Electron 4+. This is also not caused by Electron exporting any new symbols.

The problem is that the detection algorithm used to determine that NodeGit is being built for Electron is not working quite right in the binding.gyp file.

If you were to fork NodeGit as a temporary solution, I would suggest the steps where we are downloading the prebuilt of OpenSSL for Electron, just enable that step always. (so long as you're just building for Electron). When my coworker gets in today, we will boot up on OSX and figure out why the patch I was working on here: https://github.com/nodegit/nodegit/pull/1623 failed to work for OSX, but worked otherwise. Once we have that figured out it should be another day or so until we can get some patches for 0.23.0 and 0.24.0 out with Electron 4 support.

**Comment by implausible** [comment] 2019-02-11 16:20
This should do it! https://github.com/nodegit/nodegit/pull/1626 It looks like I missed some references to the old way of detecting if we were in electron.

**Comment by implausible** [comment] 2019-02-12 16:52
Just wrapping up some windows builds. I hope to have 0.23.1 and 0.24.1 out today.

**Comment by implausible** [comment] 2019-02-12 17:28
0.23.1 is out now.

**Comment by implausible** [comment] 2019-02-12 17:54
0.24.1 is out.

**Comment by implausible** [comment] 2019-02-12 17:54
This issue should be resolved. Let me know if there are any further issues.

**Closed by implausible** 2019-02-12 17:54 UTC

**Comment by tommoor** [comment] 2019-02-22 23:33
@implausible thanks for your work and turning this one around fast, much appreciated 🙏

**Comment by autr** [comment] 2020-10-27 16:16
Hello, I am having this same bug:

MacOS High Sierra
Node v13.12.0
nodegit 0.27.0
Electron 6.1.11

```
App threw an error during load
[1] Error: dlopen(/Users/Gilbert/Code/multigit/node_modules/nodegit/build/Release/nodegit.node, 1): Symbol not found: _EVP_aes_128_cbc
[1]   Referenced from: /Users/Gilbert/Code/multigit/node_modules/nodegit/build/Release/nodegit.node
[1]   Expected in: flat namespace
```
