### ISSUE TITLE
nodegit doesn't return control to the calling application

### ISSUE THREAD

**Issue by dancrumb** [nodegit/nodegit#497] opened 2015-03-19 17:14 UTC
I have the following code

```javascript
var cloneOptions = {};
cloneOptions.remoteCallbacks = {
    credentials: function(url, userName) {
        return NodeGit.Cred.sshKeyFromAgent(userName);
    }
};
logger.info('Cloning snapshot repo');
var getMostRecentCommit = function(repository) {
    return repository.getBranchCommit('master');
};

var getCommitMessage = function(commit) {
    return commit.message();
};
NodeGit.Clone(remoteRepo, path.join('_deployments',deployFolderName), cloneOptions )
    .then(getMostRecentCommit, function() { logger.error('error %o', arguments);})
    .then(getCommitMessage, function() { logger.error('error %o', arguments);})
    .then(function(message) {
        return logger.info(message);
    }, function() { logger.error('error %o', arguments);});

```

This is largely copypasta from your site.

The `NodeGit.*` chain is working fine; the repo is being cloned and I'm getting the right commit message.

However, my application then just sits and waits. There's no indication in the nodegit docs that I need to manually resolve the Promise or anything like in order for my application to complete.

What am I missing here? Or is this a nodegit bug?

**Comment by tbranyen** [comment] 2015-03-19 17:30
How is it being used? Run that code in a single file and it'll exit just fine.  Is *your* application hanging, because it's a server or something?

**Comment by johnhaley81** [comment] 2015-03-19 17:31
How large is your repository? Have you set up any [progress callbacks](http://www.nodegit.org/api/remote_callbacks/#transferProgress)?

**Comment by dancrumb** [comment] 2015-03-19 18:17
@johnhaley81 the repo isn't that large and it's progressing fine (I added the callback to confirm). 

The commit message *is* being reported, so we're getting that far. It's just that the application isn't closing.

**Comment by dancrumb** [comment] 2015-03-19 18:21
@tbranyen it's a CLI app and, when I remove the `NodeGit` chain, it completes without any problems.

**Comment by tbranyen** [comment] 2015-03-19 18:21
@dancrumb can you confirm if you run that code standalone on the CLI it exits?

**Comment by johnhaley81** [comment] 2015-03-19 18:21
@dancrumb can you add a `.done` on the end of the chain?

**Comment by dancrumb** [comment] 2015-03-19 19:39
I ran the script at https://gist.github.com/dancrumb/1b437d2d1da8b88ea62b and got the output:

```zsh
$ node test.js                                                                                                                                                                                                  
[DEBUG]: Remote stash repo: ssh://git@stash.vodori.com:2121/ps/pepper-demo-site.git
[DEBUG]: Cloning into _deployments/test
[INFO]: Cloning snapshot repo
[INFO]: v3.12.3

[INFO]: Donezo

```

where it just waits

**Comment by tbranyen** [comment] 2015-03-19 19:46
@dancrumb unfortunately that test case uses a logging tool that could be causing a problem:

here is a reduced test case I used that worked perfectly:

``` javascript
var path    =  require('path');
var NodeGit = require('./nodegit');

// create tmp folder
var deployFolderName = 'test';

// clone into tmp folder
var remoteRepo = 'git@github.com:nodegit/test';
var cloneOptions = {};
cloneOptions.remoteCallbacks = {
    credentials: function(url, userName) {
        return NodeGit.Cred.sshKeyFromAgent(userName);
    },
    transferProgress: function(info) {
      return console.log(info);
    }
};
var getMostRecentCommit = function(repository) {
    return repository.getBranchCommit('master');
};

var getCommitMessage = function(commit) {
    return commit.message();
};
NodeGit.Clone(remoteRepo, path.join('_deployments',deployFolderName), cloneOptions )
    .then(getMostRecentCommit, function() { console.log('error %o', arguments);})
    .then(getCommitMessage, function() { console.log('error %o', arguments);})
    .then(function(message) {
        return console.log(message);
    }, function() { console.log('error %o', arguments);})
    .done(function() {
        console.log('Donezo');
    });
```

**Comment by tbranyen** [comment] 2015-03-19 19:47
Whoops, sorry about that, absentmindedly clicked that.

**Comment by dancrumb** [comment] 2015-03-19 20:02
I ran

```javascript
var path    =  require('path');
var NodeGit = require('nodegit');

// create tmp folder
var deployFolderName = 'test';

// clone into tmp folder
var remoteRepo = 'ssh://git@stash.vodori.com:2121/ps/pepper-demo-site.git';
console.log('Remote stash repo: %s', remoteRepo);
console.log('Cloning into %s', path.join('_deployments',deployFolderName));
var cloneOptions = {};
cloneOptions.remoteCallbacks = {
    credentials: function(url, userName) {
        return NodeGit.Cred.sshKeyFromAgent(userName);
    }
};
console.log('Cloning snapshot repo');
var getMostRecentCommit = function(repository) {
    return repository.getBranchCommit('master');
};

var getCommitMessage = function(commit) {
    return commit.message();
};
NodeGit.Clone(remoteRepo, path.join('_deployments',deployFolderName), cloneOptions )
    .then(getMostRecentCommit, function() { console.log('error %o', arguments);})
    .then(getCommitMessage, function() {console.log('error %o', arguments);})
    .then(function(message) {
        return console.log(message);
    }, function() { console.log('error %o', arguments);})
    .done(function() {
        console.log('Donezo');
    });
```

and see the same behaviour.

I'm on Mint Linux, in a zshell on node 0.10.33

What are you on?

**Comment by dancrumb** [comment] 2015-03-19 20:04
I also checked with `git@github.com:nodegit/test`... same problem (which is what I expected, but figured was worth checking)

**Comment by dancrumb** [comment] 2015-03-19 20:13
Also seen on a Mac, zshell, node 0.11.14

**Comment by johnhaley81** [comment] 2015-03-19 20:16
I'm getting the same behavior as @dancrumb. It just hangs. Looking into it more.

**Comment by dancrumb** [comment] 2015-03-19 20:17
Just to close the loop, I just confirmed this in a Bash shell as well (on my Linux box)

**Comment by johnhaley81** [comment] 2015-03-19 20:33
I've narrowed it down to 

``` javascript
var cloneOptions = {};
cloneOptions.remoteCallbacks = {
    credentials: function(url, userName) {
        return NodeGit.Cred.sshKeyFromAgent(userName);
    }
};
```

If the callback is removed and you try to clone from a public repo it will work.

Try this @dancrumb:

``` javascript
var path    =  require('path');
var NodeGit = require('nodegit');

// create tmp folder
var deployFolderName = 'test';

// clone into tmp folder
var remoteRepo = 'git@github.com:nodegit/test';
console.log('Remote stash repo: %s', remoteRepo);
console.log('Cloning into %s', path.join('_deployments',deployFolderName));
var cloneOptions = {};

console.log('Cloning snapshot repo');
var getMostRecentCommit = function(repository) {
    return repository.getBranchCommit('master');
};

var getCommitMessage = function(commit) {
    return commit.message();
};
NodeGit.Clone(remoteRepo, path.join('_deployments',deployFolderName), cloneOptions )
    .then(getMostRecentCommit, function() { console.log('error %o', arguments);})
    .then(getCommitMessage, function() {console.log('error %o', arguments);})
    .then(function(message) {
        return console.log(message);
    }, function() { console.log('error %o', arguments);})
    .done(function() {
        console.log('Donezo');
    });
```

**Comment by tbranyen** [comment] 2015-03-19 20:34
Yeah, but then it won't actually clone it?

**Comment by johnhaley81** [comment] 2015-03-19 20:35
It will for a public repo. This is just a test to confirm what I'm seeing.

**Comment by johnhaley81** [comment] 2015-03-19 20:38
If my hypothesis is correct then I'm lead to believe that the queueing of the callbacks via `uv_async_init` and `uv_async_send` is causing the main node loop to never get the kill signal.

This might be related to #438

**Comment by johnhaley81** [comment] 2015-03-19 20:47
So it clones it for me but not on other machines. I must have some agent authenticating the connection or something. Well change it to our http test repo (http://git.tbranyen.com/smart/site-content) and try that.

**Comment by amitaibu** [comment] 2015-03-19 22:46
As I'm seeing this issue as-well, the result I get from executing @johnhaley81's code:

```
Remote stash repo: git@github.com:nodegit/test
Cloning into _deployments/test
Cloning snapshot repo
error %o { '0': [Error: authentication required but no callback set] }
error %o { '0': [TypeError: Cannot read property 'message' of undefined] }
Donezo
```

**Comment by johnhaley81** [comment] 2015-03-19 23:05
@amitaibu did you try setting `var remoteRepo = 'http://git.tbranyen.com/smart/site-content';`?

**Comment by amitaibu** [comment] 2015-03-19 23:09
Did now, and it worked fine:

```
Remote stash repo: http://git.tbranyen.com/smart/site-content
Cloning into _deployments/test
Cloning snapshot repo
Marked as lesser importance

Donezo
```

**Comment by johnhaley81** [comment] 2015-03-19 23:14
This seems like a bug in our library. I'll mark it as such and we'll try to figure it out.

In the meantime, you could put `process.exit()` in the `.done` method.

**Comment by JediMindtrick** [comment] 2015-03-22 17:43
In the case of this happening in the context of a long-running process (i.e. express server) do you think the hang would be a problem?  A little concerned that maybe it's hanging onto some kind of open connection and that over time this might cause problems...

**Comment by tbranyen** [comment] 2015-03-22 18:52
@JediMindtrick I seriously doubt it's hanging on to any kind of connection, @johnhaley81 is usually right about his hunches: https://github.com/nodegit/nodegit/issues/497#issuecomment-83754567

**Comment by johnhaley81** [comment] 2015-03-23 03:38
@tbranyen well I've definitely been wrong before :)

@JediMindtrick if you want to try it out write a quick script that uses callback functions in the processing of a call that does open any connections. `Nodegit.Status.foreach` would do the trick. It should still hang after your script is finished processing.

I'm definitely looking into this more but at least we have a sort of work-around for right now.

**Comment by johnhaley81** [comment] 2015-04-20 20:11
The handles that were created for callback's being executed on the main thread needed to be cleaned up via `uv_close`. That's about to get merged into master which should fix this.

**Closed** 2015-04-20 21:57 UTC
Labels: Bug

**Comment by juanbrujo** [comment] 2015-04-22 18:31
@johnhaley81 suggestion https://github.com/nodegit/nodegit/issues/497#issuecomment-83798391 definetly worked

**Comment by johnhaley81** [comment] 2015-04-22 18:38
@juanbrujo this will be fixed in the next release FYI.

**Comment by JediMindtrick** [comment] 2015-04-22 21:02
@johnhaley81  Thanks for fixing this.

**Comment by kevindashgit** [comment] 2016-03-26 00:42
> In the meantime, you could put process.exit() in the .done method.

**Comment by dancrumb** [comment] 2016-03-26 02:58
You're probably better off open up a new issue with your failing choice

**Comment by tbranyen** [comment] 2016-03-26 07:31
Also, @kevindashgit you offered no additional information necessary for us to assist you. Can you provide OS, Node version, NodeGit version, prebuilt or built from source, and the script that is failing?

No need to open a new issue, but if you want more rapid help, drop into our [Gitter](http://gitter.im/nodegit/nodegit)

**Comment by kevindashgit** [comment] 2016-03-28 21:02
More info:

**Comment by kevindashgit** [comment] 2016-03-28 22:27
More Info:

OS: OSX El Capitan v10.11.1
Node Version: 1.2.0.10
NodeGit Version: ^0.11.9 (prebuilt)
Script:
```
cloneOptions.fetchOpts = {
      callbacks: {
        certificateCheck: function() { return 1; },
        credentials: function(GITLAB_URL, userName) {
          console.log('help im stuck in an infinite loop');
          return NodeGit.Cred.sshKeyFromAgent(userName);
        },
        transferProgress: function(info) {
          return console.log(info);
        }
      }
    };

    var getMostRecentCommit = function(repository) {
        return repository.getBranchCommit('master');
    };

    var getCommitMessage = function(commit) {
        return commit.message();
    };
    NodeGit.Clone(siteUrl, path.join(__dirname, 'sites', test.name), cloneOptions)
        .then(getMostRecentCommit, function() { console.log('error %o', arguments);})
        .then(getCommitMessage, function() { console.log('error %o', arguments);})
        .then(function(message) {
            return console.log(message);
        }, function() { console.log('error %o', arguments);})
        .done(function() {
            console.log('Donezo');
            process.exit();
        });
```

**Comment by tbranyen** [comment] 2016-03-28 23:02
Thanks so much for updating us with some more information, I'm probably not the best one to diagnose, but I'll try and reproduce locally to at least verify.

Ping @johnhaley81 who can assist, or know who best to assist.

**Comment by johnhaley81** [comment] 2016-03-29 00:15
@kevindashgit you're giving back wrong credentials and NodeGit will ask you for creds until you either pass back one that works or pass back `NodeGit.Cred.defaultNew()`
