### ISSUE TITLE
fileHistoryWalk: max_count should be equal to the returned array size

### ISSUE THREAD

**Issue by czb** [nodegit/nodegit#1263] opened 2017-04-06 08:34 UTC
The parameter `max_count` in `fileHistoryWalk` as it is now relates to the number of iterated commits irrespective of if the commit contains the requested file or not.

I think the `max_count` could be changed such that it is the number of `returned commits` and not the number of `iterated commits` that it relates to.

Or an another function parameter could be added that specifies the maximum number of returned commits:

```
fileHistoryWalk(file, max_iterated_count, max_returned_count)
```

where for loop ends when either `max_iterated_count` or `max_returned_count` is satisfied.

**Comment by rcjsuen** [comment] 2017-04-06 09:57
Also see #1068 and #1174. Probably can mark it as a duplicate of one of those...? What do you think, @czb?

**Comment by czb** [comment] 2017-04-06 10:58
@rcjsuen the last comment from #1068 by @Kovensky is the problem that I face ;)

**Comment by rcjsuen** [comment] 2017-04-06 11:53
@czb Believe me, I am also annoyed by this. :P

**Closed by rcjsuen** 2017-04-06 11:53 UTC
