### ISSUE TITLE
getStatus hangs

### ISSUE THREAD

**Issue by AdamStone** [nodegit/nodegit#537] opened 2015-04-11 06:37 UTC
I'm trying the [status example](https://github.com/nodegit/nodegit/blob/master/examples/status.js) and finding that if uncommitted changes are present, although the example seems to work (prints `filename MODIFIED`), it doesn't return and I have to `ctrl+C`. I tried adding `.done()` at the end of each promise chain, but nothing gets thrown. 

This also happens if I remove the details after `getStatus()`, but not if I remove `getStatus()` entirely, so this seems to originate in the `getStatus()` call itself. But if the directory is clean, it does return without printing anything. 

Npm installed `^0.3.3`.

Anyone know what's going on here?

**Comment by tbranyen** [comment] 2015-04-11 06:40
Looks to be a duplicate of: https://github.com/nodegit/nodegit/issues/497

**Comment by AdamStone** [comment] 2015-04-11 06:43
D'oh, I tried to search but I guess I was too focused on status/getStatus.

**Closed** 2015-04-11 06:51 UTC

**Comment by tommoor** [comment] 2016-12-07 18:02
I'm still seeing this behavior in the latest 0.16 release - `getStatus` does not resolve sporadically

**Comment by heath-guidewire** [comment] 2017-04-06 20:17
I'm still seeing this on 0.18.0.  The first call to this method in my tests returns, the next one does not return and the .then() is not executed

**Comment by tommoor** [comment] 2017-04-06 20:21
@heath-guidewire we ended up completely removing use of getStatus from our code, instead using diffing the index to working tree using `NodeGit.Diff`. Maybe that's a strategy you could take…

**Comment by heath-guidewire** [comment] 2017-04-06 20:22
Is there an example for this?

**Comment by tommoor** [comment] 2017-04-06 20:29
Not sure about examples, but there is a method for it which works well and provides similar results to getStatus with a bit of massaging http://www.nodegit.org/api/diff/#indexToWorkdir

Something along the lines of:

```javascript
Git.Diff.indexToWorkdir(repo, null, yourDiffOptions)
.then(diff => {
  const changes = {};
  for (let i = 0; i < diff.numDeltas(); i++) {
    const delta = diff.getDelta(i);
    const oldPath = delta.oldFile().path();
    const newPath = delta.newFile().path();
    const statusPath = oldPath || newPath;
    changes[statusPath] = delta.status();
  }
  return changes;
})
  
```

**Comment by heath-guidewire** [comment] 2017-04-06 21:17
Hmm, even that command seems to have the same issue... Sometimes it works and sometimes it doesn't.

**Comment by tommoor** [comment] 2017-04-06 21:19
We've not seen any issues with that one (across tens of thousands of commits), I'd definitely check the rest of your code thoroughly, sounds like this might not be where your issue lies.

**Comment by heath-guidewire** [comment] 2017-04-06 22:08
I'm seeing a weird issue where repository.refreshIndex() does not return:  Here's the code I have
```
  let repository;
  return nodegit.Repository.open(gitRepoPath())
    .then(repo => {
      repository = repo;
      console.log('repo opened');
      return repository.refreshIndex()
        .then(index => {
          console.log('read index', index);
          const flags = nodegit.Diff.OPTION.SHOW_UNTRACKED_CONTENT | nodegit.Diff.OPTION.RECURSE_UNTRACKED_DIRS;
          const diffOptions = {flags};
          return nodegit.Diff.indexToWorkdir(repository, index, diffOptions)
            .then(diff => {
              console.log('changes found', diff);
              const changes = {};
              for (let i = 0; i < diff.numDeltas(); i++) {
                const delta = diff.getDelta(i);
                const oldPath = delta.oldFile().path();
                const newPath = delta.newFile().path();
                const statusPath = oldPath || newPath;
                changes[statusPath] = delta.status();
              }
              return changes;
            })
            .catch(error => {
              console.log('exception', error);
            })
        })
    })  let repository;
  return nodegit.Repository.open(gitRepoPath())
    .then(repo => {
      repository = repo;
      console.log('repo opened');
      return repository.refreshIndex()
        .then(index => {
          console.log('read index', index);
          const flags = nodegit.Diff.OPTION.SHOW_UNTRACKED_CONTENT | nodegit.Diff.OPTION.RECURSE_UNTRACKED_DIRS;
          const diffOptions = {flags};
          return nodegit.Diff.indexToWorkdir(repository, index, diffOptions)
            .then(diff => {
              console.log('changes found', diff);
              const changes = {};
              for (let i = 0; i < diff.numDeltas(); i++) {
                const delta = diff.getDelta(i);
                const oldPath = delta.oldFile().path();
                const newPath = delta.newFile().path();
                const statusPath = oldPath || newPath;
                changes[statusPath] = delta.status();
              }
              return changes;
            })
            .catch(error => {
              console.log('exception', error);
            })
        })
    })
```
