### ISSUE TITLE
Cannot install on Windows 10 / Py 2.7 / Error 

### ISSUE THREAD

**Issue by MocanuMarius** [nodegit/nodegit#765] opened 2015-10-26 01:21 UTC
Anyone else encountered this?

https://gist.github.com/MocanuMarius/39065cd07b29991f4855

**Comment by af7** [comment] 2015-10-26 14:29
Yes, many of us, see other same issue here:

https://github.com/nodegit/nodegit/issues/756

This issue blocks our development (for Windows), I hope for a quick resolution if possible. Thank you in advance.

**Comment by johnhaley81** [comment] 2015-10-26 18:06
@af7 Yes we are working on figuring out what's going wrong with downloading the pre-built binary. Sorry for the delay.

**Comment by johnhaley81** [comment] 2015-10-26 18:07
Closing this out as a duplicate of #756

**Closed by johnhaley81** 2015-10-26 18:07 UTC

**Comment by af7** [comment] 2015-10-27 08:08
@johnhaley81 Thanks!
